
#logging:
#  level:
#    org:
#      springframework:
#        beans: debug
#        context: debug
#      hibernate:
#        type:
#          descriptor:
 #           sql: trace

jwt:
  secret: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALaw0slD+0sRiDw4NEi0uIS88FQ5WPBSxBgjFzOK4TWjGVehHHVSNOOvMBNFMCyMhkXkgDgQArwjIKSGptK7MY0CAwEAAQ==
  
spring:
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    check-template-location: true
    mode: HTML
  redis:
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
    host: localhost
    port: 6379
  datasource:
    url: jdbc:oracle:thin:@192.168.0.27:1521:XE
    username: SCOTT
    password: tiger
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
        
#    defer-datasource-initialization: true   
##   sql\ucd08\uae30\ud654  
#  sql:
#    init:
#      mode: always
#      schema-locations:
#      - classpath:
#      data-locations:
#      - classpath:
#      continue-on-error: true
server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true